[JSH] Logger class and pre-commit hooks
jsabahu/AIDL24_SelfDriving pull request #7
Opened 2024-05-18 16:08 UTC by jsabahu

2024-05-19 10:15 UTC, MarcRamonMoreno commented on src/logger.py
> +        )
Per a donar robustesa al codi i poder tenir una traçabilitat en el cas que hi hagi un bug i entendre que aquesta passant recomano posar aquest tipus de codi després de trobar el path del directori log.

```python
        if not os.path.exists(log_folder):
            os.makedirs(log_folder)
```

2024-05-19 10:25 UTC, MarcRamonMoreno requested changes

2024-05-19 10:25 UTC, MarcRamonMoreno commented on src/logger.py
> +        file_handler = logging.FileHandler(os.path.join(log_folder, log_file))
Comprova si el registre ja té handler per a evitar afegir més d'un.

```python
        if not self.logger.handlers:
            file_handler = logging.FileHandler(os.path.join(log_folder, log_file))
            formatter = logging.Formatter(
                "%(asctime)s - %(pathname)s[line:%(lineno)d] - %(levelname)s - %(message)s"
            )
            file_handler.setFormatter(formatter)
            self.logger.addHandler(file_handler)

            console_handler = logging.StreamHandler()  
            console_handler.setFormatter(formatter)  
            self.logger.addHandler(console_handler)  # Afegeix un gestor de consola (opcional)

```

2024-05-23 19:54 UTC, jsabahu commented
Em falta possar molts parametres a la config... pero demoment intentem fer merge a dev

2024-05-25 06:50 UTC, MarcRamonMoreno submitted a review, later dismissed

2024-05-25 08:58 UTC, merged