Marc gine
jsabahu/AIDL24_SelfDriving pull request #8
Opened 2024-05-19 14:06 UTC by ginesabata

The 'Train' function has been added "without pretraining".
    There are black-box optimizer and function components, which, if necessary, could be programmed in "utils", although they 
     may not be as efficient.

Hyperparameters used in the training have been added.

A precision function has been added to "utils". This point is based on practice 3 of the subject "Projects".

2024-05-20 15:10 UTC, MarcRamonMoreno commented on src/train.py
> +        print(f"Train Epoch {epoch} loss={train_loss:.2f} acc={train_acc:.2f}")
Aqui en comptes de printf podem enviar aquest missatge per logging.info
`        logging.info(f"Train Epoch {epoch} loss={train_loss:.2f} acc={train_acc:.2f}")`

2024-05-20 15:12 UTC, MarcRamonMoreno commented on src/train.py
> +    return model
Abans de retornar el model pots guardar el millor model i la millor train_loss i enviar-la per logging.info.
```python
        # Save the best model
        if train_loss < best_loss:
            best_loss = train_loss
            torch.save(model.state_dict(), 'best_model.pth') # S'hauria d'especificar el path per guardar aquest model
            logging.info(f"Saved best model with loss {best_loss:.2f}")
```

2024-05-23 20:04 UTC, jsabahu requested changes

2024-05-23 20:04 UTC, jsabahu commented on src/train.py
> +    model = Model1(num_classes=1).to(device)  # Just one class: "LINE ROAD"?<-
Segurament seran dues. 1 pel background, y laltre per les lines del carril

2024-05-24 15:50 UTC, closed without merging